name: CI
on: [push]
jobs:
  Scheduled_Lighthouse_Test:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse on prod url and upload data to a private LHCI server.
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./lighthouserc.json
          urls: |
            https://www.coinhako.com
          uploadArtifacts: true # save results as an action artifact
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Notify when lighthouse score below expected
        run: |
          echo "this is the result ${{ steps.lighthouse.outputs.assertionResults }}"
          echo "this is the links ${{ steps.lighthouse.outputs.links }}"
          echo "this is the result path ${{ steps.lighthouse.outputs.resultspath }}"
          echo "this is the manifest ${{ steps.lighthouse.outputs.manifest }}"
